### ISSUE TITLE
$PERL5LIB for macOS Sierra

### ISSUE THREAD

**Issue by ariutta** [hexmode/mediawiki-git-remote#4]
I'm running macOS Sierra 10.12.6 with Xcode installed. When I ran `git clone mediawiki::http://git-media.wiki/w`, it gave me this error:
> Can't locate Git.pm in @INC

To fix, I needed to add another path to PERL5LIB:

```
PERL5LIB=$PERL5LIB:/Applications/Xcode.app/Contents/Developer/usr/share/git-core/perl
```

I can make a pull request with that exact line, but that's not very generalizable. Not sure how to best fix the error I ran into.

**Comment by hexmode** [comment]
I'd like to merge this with [https://github.com/Git-Mediawiki/Git-Mediawiki/](the parent project now that it has life again.  Could you try the upstream version and see if it has the same problem?
